services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data   # 👈 Mounts your local ./data folder into /data inside the container
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: false
